version: "3"
services:
  php:
    container_name: php
    build:
      context: ./
    ports:
      - 8000:8000
    volumes:
      - ./app:/var/www/html

  mysql:
    container_name: mysql
    image: mariadb:10.5.4
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=example
      - UPLOAD_LIMIT=100000000
